import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateUsers1764033394264 implements MigrationInterface {
    name = 'CreateUsers1764033394264'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "username" character varying(60) NOT NULL, "name" character varying NOT NULL, "email" character varying(320) NOT NULL, "password" character varying(255) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_users_username" UNIQUE ("username"), CONSTRAINT "uq_users_email" UNIQUE ("email"), CONSTRAINT "pk_users_id" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
