import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateCustomer1764294298713 implements MigrationInterface {
    name = 'CreateCustomer1764294298713'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "customers" ("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(100) NOT NULL, "cpfCnpj" character varying(20) NOT NULL, "email" character varying(320) NOT NULL, "phone" character varying(15) NOT NULL, "address" character varying(200) NOT NULL, "addressNumber" character varying(20) NOT NULL, "complement" character varying(100), "postalCode" character varying(10) NOT NULL, CONSTRAINT "uq_customers_cpfCnpj" UNIQUE ("cpfCnpj"), CONSTRAINT "pk_customers_id" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "customers"`);
    }

}
